// Mocks generated by Mockito 5.4.6 from annotations
// in kira_flutter_client/test/calendar/session_swipe_marks_completed.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:collection' as _i2;
import 'dart:ui' as _i8;

import 'package:kira_flutter_client/models/session_model.dart' as _i7;
import 'package:kira_flutter_client/models/task_dto.dart' as _i5;
import 'package:kira_flutter_client/providers/goals_provider.dart' as _i3;
import 'package:kira_flutter_client/ui/schedule/schedule_provider.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUnmodifiableListView_0<E> extends _i1.SmartFake
    implements _i2.UnmodifiableListView<E> {
  _FakeUnmodifiableListView_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAsyncValue_1<T> extends _i1.SmartFake implements _i3.AsyncValue<T> {
  _FakeAsyncValue_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ScheduleProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockScheduleProvider extends _i1.Mock implements _i4.ScheduleProvider {
  MockScheduleProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UnmodifiableListView<_i5.TaskDto> get tasks =>
      (super.noSuchMethod(
            Invocation.getter(#tasks),
            returnValue: _FakeUnmodifiableListView_0<_i5.TaskDto>(
              this,
              Invocation.getter(#tasks),
            ),
          )
          as _i2.UnmodifiableListView<_i5.TaskDto>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> fetchToday() =>
      (super.noSuchMethod(
            Invocation.method(#fetchToday, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateStatus(int? id, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, [id, status]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i3.AsyncValue<List<_i7.SessionModel>> watchSessionsForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#watchSessionsForDate, [date]),
            returnValue: _FakeAsyncValue_1<List<_i7.SessionModel>>(
              this,
              Invocation.method(#watchSessionsForDate, [date]),
            ),
          )
          as _i3.AsyncValue<List<_i7.SessionModel>>);

  @override
  _i6.Future<void> completeSession(int? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#completeSession, [sessionId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void initWithSeedSessions(List<_i7.SessionModel>? sessions) =>
      super.noSuchMethod(
        Invocation.method(#initWithSeedSessions, [sessions]),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Stream<String> runSchedule(String? userInput, {bool? asJson = false}) =>
      (super.noSuchMethod(
            Invocation.method(#runSchedule, [userInput], {#asJson: asJson}),
            returnValue: _i6.Stream<String>.empty(),
          )
          as _i6.Stream<String>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
