// Mocks generated by Mockito 5.4.6 from annotations
// in kira_flutter_client/test/chat/chat_typing_indicator_visible.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:kira_flutter_client/llm/llama_bridge.dart' as _i3;
import 'package:kira_flutter_client/services/websocket_service.dart' as _i2;
import 'package:kira_flutter_client/ui/chat/chat_provider.dart' as _i4;
import 'package:kira_flutter_client/ui/chat/message_dto.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWebSocketService_0 extends _i1.SmartFake
    implements _i2.WebSocketService {
  _FakeWebSocketService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLlamaBridge_1 extends _i1.SmartFake implements _i3.LlamaBridge {
  _FakeLlamaBridge_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatProvider extends _i1.Mock implements _i4.ChatProvider {
  MockChatProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WebSocketService get ws =>
      (super.noSuchMethod(
            Invocation.getter(#ws),
            returnValue: _FakeWebSocketService_0(this, Invocation.getter(#ws)),
          )
          as _i2.WebSocketService);

  @override
  _i3.LlamaBridge get gemma =>
      (super.noSuchMethod(
            Invocation.getter(#gemma),
            returnValue: _FakeLlamaBridge_1(this, Invocation.getter(#gemma)),
          )
          as _i3.LlamaBridge);

  @override
  bool get isFake =>
      (super.noSuchMethod(Invocation.getter(#isFake), returnValue: false)
          as bool);

  @override
  List<_i5.MessageDto> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: <_i5.MessageDto>[],
          )
          as List<_i5.MessageDto>);

  @override
  bool get isTyping =>
      (super.noSuchMethod(Invocation.getter(#isTyping), returnValue: false)
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> initCache() =>
      (super.noSuchMethod(
            Invocation.method(#initCache, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> fetchHistory() =>
      (super.noSuchMethod(
            Invocation.method(#fetchHistory, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> send(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#send, [text]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Stream<String> runChat(String? userInput) =>
      (super.noSuchMethod(
            Invocation.method(#runChat, [userInput]),
            returnValue: _i6.Stream<String>.empty(),
          )
          as _i6.Stream<String>);

  @override
  _i6.Future<String> debugBuildPrompt(String? userInput) =>
      (super.noSuchMethod(
            Invocation.method(#debugBuildPrompt, [userInput]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#debugBuildPrompt, [userInput]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
