name: kira_flutter_client
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  provider: ^6.1.0
  go_router: ^13.0.0
  flutter_chat_ui: 2.5.2
  intl: ^0.19.0
  timeline_tile: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  
  web_socket_channel: ^3.0.3
  uuid: ^4.3.3
  sqflite: ^2.3.2
  path_provider: ^2.1.3
  path: ^1.9.0
  sqlite3_flutter_libs: ^0.5.21
  integration_test:
    sdk: flutter

  sqflite_common_ffi: any
  ffi: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_lints: ^6.0.0

  async: any
  stream_channel: any
flutter:
  uses-material-design: true
  assets:
    - .env
